const ROUND_CONFIG = {
    1: { name: "Round 1 – સામાન્ય જ્ઞાન", timer: 30, isBuzzer: false, limit: 30},
    99: { name: "⚠️ TIE BREAKER ⚠️", timer: 15, isBuzzer: true, limit: 3}
};
const quizQuestions = [
    // ROUND 1 (Buzzer)
	{ roundId: 1, question: "What is the capital city of Canada?", options: { A: "Toronto", B: "Ottawa", C: "Vancouver", D: "Montreal" }, answer: "B", image: null },
	{ roundId: 1, question: "Which ocean is on Canada's west coast?", options: { A: "Atlantic Ocean", B: "Indian Ocean", C: "Pacific Ocean", D: "Arctic Ocean" }, answer: "C", image: null },
	{ roundId: 1, question: "How many provinces does Canada have?", options: { A: "8", B: "10", C: "12", D: "13" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the longest river in Canada?", options: { A: "Fraser River", B: "St. Lawrence River", C: "Mackenzie River", D: "Yukon River" }, answer: "C", image: null },
	{ roundId: 1, question: "Which leaf appears on the Canadian flag?", options: { A: "Oak", B: "Maple", C: "Pine", D: "Birch" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the largest planet in our Solar System?", options: { A: "Earth", B: "Mars", C: "Jupiter", D: "Saturn" }, answer: "C", image: null },
	{ roundId: 1, question: "Which gas do plants absorb from the air?", options: { A: "Oxygen", B: "Carbon Dioxide", C: "Nitrogen", D: "Helium" }, answer: "B", image: null },
	{ roundId: 1, question: "How many sides does a hexagon have?", options: { A: "5", B: "6", C: "7", D: "8" }, answer: "B", image: null },
	{ roundId: 1, question: "Which continent is Canada located in?", options: { A: "Europe", B: "Asia", C: "North America", D: "South America" }, answer: "C", image: null },
	{ roundId: 1, question: "What is the freezing point of water?", options: { A: "0°C", B: "10°C", C: "32°C", D: "100°C" }, answer: "A", image: null },
	{ roundId: 1, question: "Which animal is Canada's national animal?", options: { A: "Moose", B: "Beaver", C: "Polar Bear", D: "Wolf" }, answer: "B", image: null },
	{ roundId: 1, question: "Which is the largest province in Canada by area?", options: { A: "Ontario", B: "British Columbia", C: "Quebec", D: "Alberta" }, answer: "C", image: null },
	{ roundId: 1, question: "What is 9 × 8?", options: { A: "64", B: "72", C: "81", D: "96" }, answer: "B", image: null },
	{ roundId: 1, question: "Which season comes after summer?", options: { A: "Spring", B: "Winter", C: "Autumn", D: "Monsoon" }, answer: "C", image: null },
	{ roundId: 1, question: "Who wrote the Harry Potter book series?", options: { A: "Roald Dahl", B: "J.K. Rowling", C: "Rick Riordan", D: "C.S. Lewis" }, answer: "B", image: null },
	{ roundId: 1, question: "Which instrument measures temperature?", options: { A: "Barometer", B: "Thermometer", C: "Compass", D: "Scale" }, answer: "B", image: null },
	{ roundId: 1, question: "Which planet is known as the Red Planet?", options: { A: "Venus", B: "Mars", C: "Mercury", D: "Neptune" }, answer: "B", image: null },
	{ roundId: 1, question: "How many hours are there in one day?", options: { A: "12", B: "18", C: "24", D: "36" }, answer: "C", image: null },
	{ roundId: 1, question: "Which Canadian province is home to Niagara Falls?", options: { A: "Ontario", B: "Quebec", C: "Manitoba", D: "Nova Scotia" }, answer: "A", image: null },
	{ roundId: 1, question: "What is the main language spoken in Quebec?", options: { A: "English", B: "French", C: "Spanish", D: "German" }, answer: "B", image: null },
    { roundId: 1, question: "Which freedom fighter from Gujarat was known as 'Dungli Chor' (Onion Thief)?", options: { A: "Mohanlal Pandya", B: "Zaverchand Meghani", C: "Ravishankar Maharaj", D: "Indulal Yagnik" }, answer: "A", image: null },
	{ roundId: 1, question: "Who founded the Maurya Empire?", options: { A: "Chandragupta Maurya", B: "Bindusara", C: "Ashoka", D: "Harshavardhana" }, answer: "A", image: null },
	{ roundId: 1, question: "Who is known as the Iron Man of India?", options: { A: "Jawaharlal Nehru", B: "Sardar Vallabhbhai Patel", C: "Lal Bahadur Shastri", D: "Bhagat Singh" }, answer: "B", image: null },
	{ roundId: 1, question: "What was the name of Lord Rama's sister?", options: { A: "Sumitra", B: "Shanta", C: "Urmila", D: "Kaushalya" }, answer: "B", image: null },
	{ roundId: 1, question: "Which musical instrument was Ravana an expert at playing?", options: { A: "Tabla", B: "Flute", C: "Veena", D: "Drum" }, answer: "C", image: null },
	{ roundId: 1, question: "Lakshman is considered an avatar of whom?", options: { A: "Sheshnag", B: "Vishnu", C: "Shiva", D: "Brahma" }, answer: "A", image: null },
	{ roundId: 1, question: "What disguise did Ravana take while kidnapping Sita?", options: { A: "King", B: "Sage", C: "Deer", D: "Monkey" }, answer: "B", image: null },
	{ roundId: 1, question: "In which Kanda of the Ramayana did Hanuman first meet Lord Rama?", options: { A: "Bala Kanda", B: "Ayodhya Kanda", C: "Kishkindha Kanda", D: "Sundara Kanda" }, answer: "C", image: null },
	{ roundId: 1, question: "Who was Karna's father?", options: { A: "Indra", B: "Surya", C: "Vayu", D: "Agni" }, answer: "B", image: null },
	{ roundId: 1, question: "What was the name of Arjuna's chariot?", options: { A: "Nandighosha", B: "Kapidhwaja", C: "Garudadhwaja", D: "Pushpaka" }, answer: "B", image: null },
	{ roundId: 1, question: "What was the name of Lord Krishna's conch?", options: { A: "Devadatta", B: "Panchajanya", C: "Paundra", D: "Anantavijaya" }, answer: "B", image: null },
	{ roundId: 1, question: "For how many days was Bhishma the commander during the Kurukshetra War?", options: { A: "10 days", B: "12 days", C: "15 days", D: "18 days" }, answer: "A", image: null },
	{ roundId: 1, question: "Who was Abhimanyu's mother?", options: { A: "Draupadi", B: "Kunti", C: "Subhadra", D: "Gandhari" }, answer: "C", image: null },
	{ roundId: 1, question: "Which is the largest ocean on Earth?", options: { A: "Atlantic Ocean", B: "Indian Ocean", C: "Arctic Ocean", D: "Pacific Ocean" }, answer: "D", image: null },
	{ roundId: 1, question: "What is the capital of India?", options: { A: "Mumbai", B: "Kolkata", C: "New Delhi", D: "Chennai" }, answer: "C", image: null },
	{ roundId: 1, question: "What is the national animal of India?", options: { A: "Lion", B: "Tiger", C: "Elephant", D: "Cheetah" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the national bird of India?", options: { A: "Pigeon", B: "Peacock", C: "Eagle", D: "Swan" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the national flower of India?", options: { A: "Rose", B: "Lotus", C: "Jasmine", D: "Sunflower" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the capital of Gujarat?", options: { A: "Ahmedabad", B: "Vadodara", C: "Gandhinagar", D: "Surat" }, answer: "C", image: null },
	{ roundId: 1, question: "Whose statue is the Statue of Unity?", options: { A: "Mahatma Gandhi", B: "Sardar Vallabhbhai Patel", C: "Subhas Chandra Bose", D: "Bhagat Singh" }, answer: "B", image: null },
	{ roundId: 1, question: "When did India gain independence?", options: { A: "15 August 1947", B: "26 January 1950", C: "2 October 1947", D: "15 August 1952" }, answer: "A", image: null },
	{ roundId: 1, question: "Who was the first President of India?", options: { A: "Dr. Rajendra Prasad", B: "Jawaharlal Nehru", C: "Dr. Sarvepalli Radhakrishnan", D: "Indira Gandhi" }, answer: "A", image: null },
	{ roundId: 1, question: "Who was the first Prime Minister of India?", options: { A: "Sardar Vallabhbhai Patel", B: "Jawaharlal Nehru", C: "Rajiv Gandhi", D: "Lal Bahadur Shastri" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the national anthem of India?", options: { A: "Vande Mataram", B: "Jana Gana Mana", C: "Sare Jahan Se Achha", D: "Jai Hind" }, answer: "B", image: null },
	{ roundId: 1, question: "When is Gujarat Foundation Day celebrated?", options: { A: "1 May", B: "15 August", C: "26 January", D: "2 October" }, answer: "A", image: null },
	{ roundId: 1, question: "Gir National Park is famous for which animal?", options: { A: "Tiger", B: "Lion", C: "Elephant", D: "Cheetah" }, answer: "B", image: null },
	{ roundId: 1, question: "In which district is the Somnath Temple located?", options: { A: "Junagadh", B: "Gir Somnath", C: "Rajkot", D: "Jamnagar" }, answer: "B", image: null },
	{ roundId: 1, question: "In which city is the Dwarkadhish Temple located?", options: { A: "Dwarka", B: "Porbandar", C: "Jamnagar", D: "Veraval" }, answer: "A", image: null },
	{ roundId: 1, question: "What is the chemical formula of water?", options: { A: "H2O", B: "CO2", C: "O2", D: "H2" }, answer: "A", image: null },
	{ roundId: 1, question: "What is Earth's natural satellite?", options: { A: "Sun", B: "Moon", C: "Mars", D: "Venus" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the speed of light?", options: { A: "300,000 km/s", B: "200,000 km/s", C: "100,000 km/s", D: "500,000 km/s" }, answer: "A", image: null },
	{ roundId: 1, question: "How many bones are there in the human body?", options: { A: "196", B: "206", C: "216", D: "226" }, answer: "B", image: null },
	{ roundId: 1, question: "What gives blood its red color?", options: { A: "Plasma", B: "Hemoglobin", C: "Platelets", D: "Water" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the process by which plants make food called?", options: { A: "Respiration", B: "Photosynthesis", C: "Digestion", D: "Excretion" }, answer: "B", image: null },
	{ roundId: 1, question: "Which is the largest ocean in the world?", options: { A: "Atlantic Ocean", B: "Pacific Ocean", C: "Indian Ocean", D: "Arctic Ocean" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the highest mountain in the world?", options: { A: "K2", B: "Mount Everest", C: "Kangchenjunga", D: "Nanga Parbat" }, answer: "B", image: null },
	{ roundId: 1, question: "The Nile River is located on which continent?", options: { A: "Asia", B: "Europe", C: "Africa", D: "Australia" }, answer: "C", image: null },
	{ roundId: 1, question: "Which is the longest river in India?", options: { A: "Ganga", B: "Yamuna", C: "Godavari", D: "Brahmaputra" }, answer: "A", image: null },
	{ roundId: 1, question: "Which is the largest desert in the world?", options: { A: "Sahara", B: "Thar", C: "Gobi", D: "Kalahari" }, answer: "A", image: null },
	{ roundId: 1, question: "How many players are there on a cricket team?", options: { A: "9", B: "10", C: "11", D: "12" }, answer: "C", image: null },
	{ roundId: 1, question: "How often are the Olympic Games held?", options: { A: "Every 2 years", B: "Every 3 years", C: "Every 4 years", D: "Every 5 years" }, answer: "C", image: null },
	{ roundId: 1, question: "Which organization organizes the FIFA World Cup?", options: { A: "ICC", B: "FIFA", C: "IOC", D: "BCCI" }, answer: "B", image: null },
	{ roundId: 1, question: "When is World Environment Day celebrated?", options: { A: "June 5", B: "June 6", C: "June 7", D: "June 8" }, answer: "A", image: null },
	{ roundId: 1, question: "When is Teachers' Day celebrated in India?", options: { A: "September 5", B: "September 10", C: "September 15", D: "September 2" }, answer: "A", image: null },
	{ roundId: 1, question: "What is the capital of India?", options: { A: "Mumbai", B: "Kolkata", C: "New Delhi", D: "Chennai" }, answer: "C", image: null },
	{ roundId: 1, question: "What is the national animal of India?", options: { A: "Lion", B: "Tiger", C: "Elephant", D: "Cheetah" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the national bird of India?", options: { A: "Peacock", B: "Pigeon", C: "Swan", D: "Eagle" }, answer: "A", image: null },
	{ roundId: 1, question: "What is the national flower of India?", options: { A: "Lotus", B: "Rose", C: "Jasmine", D: "Sunflower" }, answer: "A", image: null },
	{ roundId: 1, question: "Which sport is traditionally recognized as the national sport of India?", options: { A: "Cricket", B: "Hockey", C: "Football", D: "Kabaddi" }, answer: "B", image: null },
	{ roundId: 1, question: "When did India gain independence?", options: { A: "15 August 1947", B: "26 January 1950", C: "2 October 1947", D: "15 August 1952" }, answer: "A", image: null },
	{ roundId: 1, question: "Who was the first Prime Minister of India?", options: { A: "Sardar Vallabhbhai Patel", B: "Jawaharlal Nehru", C: "Lal Bahadur Shastri", D: "Rajiv Gandhi" }, answer: "B", image: null },
	{ roundId: 1, question: "Who was the first President of India?", options: { A: "Dr. Rajendra Prasad", B: "Dr. Sarvepalli Radhakrishnan", C: "Jawaharlal Nehru", D: "Indira Gandhi" }, answer: "A", image: null },
	{ roundId: 1, question: "What is the capital of Gujarat?", options: { A: "Ahmedabad", B: "Surat", C: "Gandhinagar", D: "Vadodara" }, answer: "C", image: null },
	{ roundId: 1, question: "When is Gujarat Foundation Day celebrated?", options: { A: "May 1", B: "August 15", C: "January 26", D: "October 2" }, answer: "A", image: null },
	{ roundId: 1, question: "Whose statue is the Statue of Unity?", options: { A: "Mahatma Gandhi", B: "Sardar Vallabhbhai Patel", C: "Subhas Chandra Bose", D: "Bhagat Singh" }, answer: "B", image: null },
	{ roundId: 1, question: "Gir National Park is famous for which animal?", options: { A: "Tiger", B: "Lion", C: "Elephant", D: "Cheetah" }, answer: "B", image: null },
	{ roundId: 1, question: "In which state is the Somnath Temple located?", options: { A: "Gujarat", B: "Rajasthan", C: "Maharashtra", D: "Madhya Pradesh" }, answer: "A", image: null },
	{ roundId: 1, question: "Dwarka is associated with which Hindu deity?", options: { A: "Shiva", B: "Vishnu", C: "Krishna", D: "Ganesha" }, answer: "C", image: null },
	{ roundId: 1, question: "Which is the largest ocean in the world?", options: { A: "Atlantic Ocean", B: "Pacific Ocean", C: "Indian Ocean", D: "Arctic Ocean" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the highest mountain in the world?", options: { A: "K2", B: "Mount Everest", C: "Kangchenjunga", D: "Nanga Parbat" }, answer: "B", image: null },
	{ roundId: 1, question: "Which is the longest river in India?", options: { A: "Ganga", B: "Yamuna", C: "Godavari", D: "Narmada" }, answer: "A", image: null },
	{ roundId: 1, question: "The Rann of Kutch is located in which state?", options: { A: "Rajasthan", B: "Gujarat", C: "Maharashtra", D: "Punjab" }, answer: "B", image: null },
	{ roundId: 1, question: "Which is the largest state in India by area?", options: { A: "Gujarat", B: "Rajasthan", C: "Maharashtra", D: "Uttar Pradesh" }, answer: "B", image: null },
	{ roundId: 1, question: "Which is the most populous state in India?", options: { A: "Bihar", B: "Gujarat", C: "Uttar Pradesh", D: "Maharashtra" }, answer: "C", image: null },
	{ roundId: 1, question: "When is World Environment Day celebrated?", options: { A: "June 5", B: "June 10", C: "June 15", D: "June 20" }, answer: "A", image: null },
	{ roundId: 1, question: "When is Teachers' Day celebrated in India?", options: { A: "September 5", B: "September 10", C: "September 15", D: "September 20" }, answer: "A", image: null },
	{ roundId: 1, question: "When is International Yoga Day celebrated?", options: { A: "June 20", B: "June 21", C: "June 22", D: "June 23" }, answer: "B", image: null },
	{ roundId: 1, question: "How many players are there on a cricket team?", options: { A: "9", B: "10", C: "11", D: "12" }, answer: "C", image: null },
	{ roundId: 1, question: "How often are the Olympic Games held?", options: { A: "Every 2 years", B: "Every 3 years", C: "Every 4 years", D: "Every 5 years" }, answer: "C", image: null },
	{ roundId: 1, question: "On which continent is India located?", options: { A: "Asia", B: "Europe", C: "Africa", D: "Australia" }, answer: "A", image: null },
	{ roundId: 1, question: "Who designed the National Flag of India?", options: { A: "Pingali Venkayya", B: "Mahatma Gandhi", C: "Subhas Chandra Bose", D: "Dr. Rajendra Prasad" }, answer: "A", image: null },
	{ roundId: 1, question: "Which is the longest river in the world?", options: { A: "Nile", B: "Amazon", C: "Ganga", D: "Yangtze" }, answer: "A", image: null },
	{ roundId: 1, question: "What is the capital of the United States?", options: { A: "New York", B: "Washington, D.C.", C: "Los Angeles", D: "Chicago" }, answer: "B", image: null },
	{ roundId: 1, question: "Which is the largest country in the world by area?", options: { A: "United States", B: "China", C: "Russia", D: "India" }, answer: "C", image: null },
	{ roundId: 1, question: "What is the National Emblem of India?", options: { A: "Ashoka Chakra", B: "Lion Capital of Ashoka", C: "Tiger", D: "Lotus" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the National Anthem of India?", options: { A: "Vande Mataram", B: "Jana Gana Mana", C: "Sare Jahan Se Achha", D: "Jai Hind" }, answer: "B", image: null },
	{ roundId: 1, question: "In which city was Mahatma Gandhi born?", options: { A: "Ahmedabad", B: "Rajkot", C: "Porbandar", D: "Surat" }, answer: "C", image: null },
	{ roundId: 1, question: "Who was the first woman Prime Minister of India?", options: { A: "Pratibha Patil", B: "Indira Gandhi", C: "Sonia Gandhi", D: "Sushma Swaraj" }, answer: "B", image: null },
	{ roundId: 1, question: "How many states are there in India?", options: { A: "26", B: "28", C: "29", D: "30" }, answer: "B", image: null },
	{ roundId: 1, question: "Which is the largest city in Gujarat?", options: { A: "Surat", B: "Ahmedabad", C: "Rajkot", D: "Vadodara" }, answer: "B", image: null },
	{ roundId: 1, question: "The Narmada River flows into which sea?", options: { A: "Arabian Sea", B: "Bay of Bengal", C: "Indian Ocean", D: "Red Sea" }, answer: "A", image: null },
	{ roundId: 1, question: "The Sabarmati River flows through which city?", options: { A: "Surat", B: "Ahmedabad", C: "Rajkot", D: "Jamnagar" }, answer: "B", image: null },
	{ roundId: 1, question: "Which is the tallest dam in India?", options: { A: "Sardar Sarovar Dam", B: "Bhakra Nangal Dam", C: "Hirakud Dam", D: "Tehri Dam" }, answer: "D", image: null },
	{ roundId: 1, question: "Which is the largest desert in the world?", options: { A: "Sahara Desert", B: "Gobi Desert", C: "Thar Desert", D: "Kalahari Desert" }, answer: "A", image: null },
	{ roundId: 1, question: "The Thar Desert is located in which country or countries?", options: { A: "India", B: "Pakistan", C: "India and Pakistan", D: "Nepal" }, answer: "C", image: null },
	{ roundId: 1, question: "Which is the largest island in the world?", options: { A: "Greenland", B: "Madagascar", C: "Sri Lanka", D: "Japan" }, answer: "A", image: null },
	{ roundId: 1, question: "Which is the longest bridge in India?", options: { A: "Bhupen Hazarika Setu", B: "Howrah Bridge", C: "Bandra-Worli Sea Link", D: "Golden Bridge" }, answer: "A", image: null },
	{ roundId: 1, question: "When is World Health Day celebrated?", options: { A: "April 7", B: "June 5", C: "October 10", D: "December 1" }, answer: "A", image: null },
	{ roundId: 1, question: "When is World Water Day celebrated?", options: { A: "March 21", B: "March 22", C: "March 23", D: "March 24" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the currency of India?", options: { A: "Dollar", B: "Rupee", C: "Yen", D: "Pound" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the national tree of India?", options: { A: "Banyan Tree", B: "Peepal Tree", C: "Neem Tree", D: "Mango Tree" }, answer: "A", image: null },
	{ roundId: 1, question: "What is the national fruit of India?", options: { A: "Apple", B: "Mango", C: "Banana", D: "Pomegranate" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the national aquatic animal of India?", options: { A: "Dolphin", B: "Whale", C: "Shark", D: "Turtle" }, answer: "A", image: null },
	{ roundId: 1, question: "Which is the most populous country in the world?", options: { A: "China", B: "India", C: "United States", D: "Indonesia" }, answer: "B", image: null },
    { roundId: 1, question: "Identify the Person", options: { A: "આલ્બર્ટ આઇન્સ્ટાઇન", B: "ગેલેલિયો", C: "બ્રુનો", D: "ન્યૂટન" }, answer: "A", image: "Images/Albert Einstain.jpg" },
    { roundId: 1, question: "25 x 4 + 10", options: { A: "100", B: "110", C: "120", D: "150" }, answer: "B", image: null },
    { roundId: 1, question: "50 x 1230?", options: { A: "65100", B: "60150", C: "61500", D: "65100" }, answer: "C", image: null },
    { roundId: 1, question: "Square root of 144 is what?", options: { A: "10", B: "12", C: "14", D: "16" }, answer: "B", image: null },
    { roundId: 1, question: "Sum of all three angles of triangle is?", options: { A: "90°", B: "180°", C: "270°", D: "360°" }, answer: "B", image: null },
    { roundId: 1, question: "5 + 7 = ?", options: { A: "10", B: "11", C: "12", D: "13" }, answer: "C", image: null },
    { roundId: 1, question: "9 × 6 = ?", options: { A: "54", B: "56", C: "52", D: "50" }, answer: "A", image: null },
    { roundId: 1, question: "15 - 8 = ?", options: { A: "5", B: "6", C: "7", D: "8" }, answer: "C", image: null },
    { roundId: 1, question: "24 ÷ 6 = ?", options: { A: "3", B: "4", C: "5", D: "6" }, answer: "B", image: null },
    { roundId: 1, question: "12 × 8 = ?", options: { A: "96", B: "92", C: "98", D: "94" }, answer: "A", image: null },
    { roundId: 1, question: "100 ÷ 5 = ?", options: { A: "15", B: "20", C: "25", D: "30" }, answer: "B", image: null },
    { roundId: 1, question: "7² = ?", options: { A: "14", B: "21", C: "49", D: "28" }, answer: "C", image: null },
    { roundId: 1, question: "√64 = ?", options: { A: "6", B: "7", C: "8", D: "9" }, answer: "C", image: null },
    { roundId: 1, question: "10% of 200 = ?", options: { A: "10", B: "15", C: "20", D: "25" }, answer: "C", image: null },
    { roundId: 1, question: "25 + 35 = ?", options: { A: "50", B: "55", C: "60", D: "65" }, answer: "C", image: null },
    { roundId: 1, question: "18 × 3 = ?", options: { A: "54", B: "56", C: "58", D: "60" }, answer: "A", image: null },
    { roundId: 1, question: "81 ÷ 9 = ?", options: { A: "7", B: "8", C: "9", D: "10" }, answer: "C", image: null },
    { roundId: 1, question: "6³ = ?", options: { A: "36", B: "216", C: "126", D: "196" }, answer: "B", image: null },
    { roundId: 1, question: "14 + 29 = ?", options: { A: "41", B: "42", C: "43", D: "44" }, answer: "C", image: null },
    { roundId: 1, question: "50 - 17 = ?", options: { A: "31", B: "32", C: "33", D: "34" }, answer: "C", image: null },
    { roundId: 1, question: "36 ÷ 4 = ?", options: { A: "7", B: "8", C: "9", D: "10" }, answer: "C", image: null },
    { roundId: 1, question: "11 × 11 = ?", options: { A: "111", B: "121", C: "131", D: "141" }, answer: "B", image: null },
    { roundId: 1, question: "45 + 55 = ?", options: { A: "95", B: "100", C: "105", D: "110" }, answer: "B", image: null },
    { roundId: 1, question: "72 ÷ 8 = ?", options: { A: "7", B: "8", C: "9", D: "10" }, answer: "C", image: null },
    { roundId: 1, question: "16² = ?", options: { A: "256", B: "196", C: "216", D: "266" }, answer: "A", image: null },
    { roundId: 1, question: "Desimal value of 3/4?", options: { A: "0.25", B: "0.5", C: "0.75", D: "1.25" }, answer: "C", image: null },
    { roundId: 1, question: "20% of 150 = ?", options: { A: "20", B: "25", C: "30", D: "35" }, answer: "C", image: null },
    { roundId: 1, question: "13 × 4 = ?", options: { A: "48", B: "50", C: "52", D: "54" }, answer: "C", image: null },
    { roundId: 1, question: "90 ÷ 10 = ?", options: { A: "8", B: "9", C: "10", D: "11" }, answer: "B", image: null },
    { roundId: 1, question: "8² = ?", options: { A: "16", B: "32", C: "64", D: "48" }, answer: "C", image: null },
    { roundId: 1, question: "1000 ÷ 100 = ?", options: { A: "5", B: "8", C: "10", D: "20" }, answer: "C", image: null },
    { roundId: 1, question: "17 + 28 = ?", options: { A: "43", B: "44", C: "45", D: "46" }, answer: "C", image: null },
    { roundId: 1, question: "60 - 25 = ?", options: { A: "30", B: "35", C: "40", D: "45" }, answer: "B", image: null },
    { roundId: 1, question: "7 × 12 = ?", options: { A: "72", B: "84", C: "96", D: "88" }, answer: "B", image: null },
    { roundId: 1, question: "144 ÷ 12 = ?", options: { A: "10", B: "11", C: "12", D: "13" }, answer: "C", image: null },
    { roundId: 1, question: "5³ = ?", options: { A: "25", B: "75", C: "125", D: "150" }, answer: "C", image: null },
    { roundId: 1, question: "√81 = ?", options: { A: "7", B: "8", C: "9", D: "10" }, answer: "C", image: null },
    { roundId: 1, question: "30% of 200 = ?", options: { A: "40", B: "50", C: "60", D: "70" }, answer: "C", image: null },
    { roundId: 1, question: "19 + 21 = ?", options: { A: "38", B: "39", C: "40", D: "41" }, answer: "C", image: null },
    { roundId: 1, question: "80 - 32 = ?", options: { A: "46", B: "47", C: "48", D: "49" }, answer: "C", image: null },
    { roundId: 1, question: "9 × 9 = ?", options: { A: "72", B: "81", C: "90", D: "99" }, answer: "B", image: null },
    { roundId: 1, question: "63 ÷ 7 = ?", options: { A: "7", B: "8", C: "9", D: "10" }, answer: "C", image: null },
    { roundId: 1, question: "4² = ?", options: { A: "8", B: "12", C: "16", D: "20" }, answer: "C", image: null },
    { roundId: 1, question: "200 ÷ 20 = ?", options: { A: "8", B: "9", C: "10", D: "12" }, answer: "C", image: null },
    { roundId: 1, question: "22 + 33 = ?", options: { A: "50", B: "55", C: "60", D: "65" }, answer: "B", image: null },    
    { roundId: 1, question: "What is the chemical formula of water?", options: { A: "H2O", B: "CO2", C: "O2", D: "H2" }, answer: "A", image: null },
	{ roundId: 1, question: "How many bones are there in the human body?", options: { A: "196", B: "206", C: "216", D: "226" }, answer: "B", image: null },
	{ roundId: 1, question: "What is Earth's natural satellite?", options: { A: "Sun", B: "Moon", C: "Mars", D: "Venus" }, answer: "B", image: null },
	{ roundId: 1, question: "What type of star is the Sun?", options: { A: "Red", B: "Yellow", C: "Blue", D: "White" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the speed of light?", options: { A: "300,000 km/s", B: "200,000 km/s", C: "100,000 km/s", D: "500,000 km/s" }, answer: "A", image: null },
	{ roundId: 1, question: "How long does Earth take to complete one orbit around the Sun?", options: { A: "365 days", B: "366 days", C: "364 days", D: "360 days" }, answer: "A", image: null },
	{ roundId: 1, question: "What is the largest organ in the human body?", options: { A: "Heart", B: "Lungs", C: "Skin", D: "Liver" }, answer: "C", image: null },
	{ roundId: 1, question: "What gives blood its red color?", options: { A: "Plasma", B: "Hemoglobin", C: "Platelets", D: "Water" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the process by which plants make food called?", options: { A: "Respiration", B: "Photosynthesis", C: "Digestion", D: "Excretion" }, answer: "B", image: null },
	{ roundId: 1, question: "Electric current is measured in which unit?", options: { A: "Volt", B: "Ampere", C: "Watt", D: "Ohm" }, answer: "B", image: null },
	{ roundId: 1, question: "Which is the largest planet in the Solar System?", options: { A: "Earth", B: "Mars", C: "Jupiter", D: "Saturn" }, answer: "C", image: null },
	{ roundId: 1, question: "Which gas is essential for life on Earth?", options: { A: "Oxygen", B: "Carbon Dioxide", C: "Nitrogen", D: "Hydrogen" }, answer: "A", image: null },
	{ roundId: 1, question: "Which organ filters blood in the human body?", options: { A: "Heart", B: "Kidneys", C: "Lungs", D: "Liver" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the center of the Earth called?", options: { A: "Crust", B: "Mantle", C: "Core", D: "Layer" }, answer: "C", image: null },
	{ roundId: 1, question: "What is the hardest natural substance?", options: { A: "Iron", B: "Diamond", C: "Gold", D: "Silver" }, answer: "B", image: null },
	{ roundId: 1, question: "In which medium does sound travel the fastest?", options: { A: "Air", B: "Water", C: "Solid", D: "Vacuum" }, answer: "C", image: null },
	{ roundId: 1, question: "What is the main function of the human heart?", options: { A: "Digestion", B: "Pump blood", C: "Breathing", D: "Thinking" }, answer: "B", image: null },
	{ roundId: 1, question: "What does water become at 100°C?", options: { A: "Ice", B: "Steam", C: "Solid", D: "Plasma" }, answer: "B", image: null },
	{ roundId: 1, question: "Why do day and night occur on Earth?", options: { A: "Earth's revolution", B: "Earth's rotation", C: "Moon's movement", D: "Sun's movement" }, answer: "B", image: null },
	{ roundId: 1, question: "Which gas is most abundant in Earth's atmosphere?", options: { A: "Oxygen", B: "Nitrogen", C: "Carbon Dioxide", D: "Hydrogen" }, answer: "B", image: null },
	{ roundId: 1, question: "Which scientist is famous for his experiments with electricity?", options: { A: "Albert Einstein", B: "Isaac Newton", C: "Benjamin Franklin", D: "Galileo Galilei" }, answer: "C", image: null },
	{ roundId: 1, question: "Who invented the telephone?", options: { A: "Alexander Graham Bell", B: "Thomas Edison", C: "Isaac Newton", D: "Albert Einstein" }, answer: "A", image: null },
	{ roundId: 1, question: "What does DNA stand for?", options: { A: "Deoxyribonucleic Acid", B: "Dynamic Nuclear Acid", C: "Digital Network Array", D: "Double Nuclear Atom" }, answer: "A", image: null },
	{ roundId: 1, question: "Which planet is closest to the Sun?", options: { A: "Mars", B: "Mercury", C: "Venus", D: "Earth" }, answer: "B", image: null },
	{ roundId: 1, question: "Which is the hottest planet in the Solar System?", options: { A: "Mercury", B: "Venus", C: "Mars", D: "Saturn" }, answer: "B", image: null },
	{ roundId: 1, question: "What does water become at 0°C?", options: { A: "Steam", B: "Ice", C: "Gas", D: "Plasma" }, answer: "B", image: null },
	{ roundId: 1, question: "Which organ helps humans breathe?", options: { A: "Heart", B: "Lungs", C: "Liver", D: "Brain" }, answer: "B", image: null },
	{ roundId: 1, question: "The brain is part of which body system?", options: { A: "Digestive System", B: "Muscular System", C: "Nervous System", D: "Respiratory System" }, answer: "C", image: null },
	{ roundId: 1, question: "What is the largest animal in the world?", options: { A: "Elephant", B: "Blue Whale", C: "Giraffe", D: "Shark" }, answer: "B", image: null },
	{ roundId: 1, question: "What type of organism is a bacterium?", options: { A: "Single-celled", B: "Multicellular", C: "Virus", D: "Fungus" }, answer: "A", image: null },
	{ roundId: 1, question: "Which gas do plants absorb during photosynthesis?", options: { A: "Oxygen", B: "Nitrogen", C: "Carbon Dioxide", D: "Hydrogen" }, answer: "C", image: null },
	{ roundId: 1, question: "Which is considered the hardest natural material?", options: { A: "Gold", B: "Iron", C: "Platinum", D: "Diamond" }, answer: "D", image: null },
	{ roundId: 1, question: "How many bones are in the adult human body?", options: { A: "206", B: "208", C: "210", D: "212" }, answer: "A", image: null },
	{ roundId: 1, question: "What is the fastest land animal?", options: { A: "Lion", B: "Cheetah", C: "Horse", D: "Tiger" }, answer: "B", image: null },
	{ roundId: 1, question: "What is the capital city of India?", options: { A: "Mumbai", B: "Ahmedabad", C: "New Delhi", D: "Chennai" }, answer: "C", image: null }
    
	// TIE BREAKER (Buzzer)
    { roundId: 99, question: "How many Teeth Aastha has?", options: { A: "32", B: "37", C: "30", D: "23" }, answer: "C", image: null},
	{ roundId: 99, question: "Which Gas is 78% in the atmosphere?", options: { A: "Oxygen", B: "Carbon Dioxide", C: "Nitrogen", D: "Hydrogen" },answer: "C", image: null},
	{ roundId: 99, question: "Who was the first female President of India?", options: { A: "Sonia Gandhi", B: "Draupadi Murmu", C: "Indira Gandhi", D: "Pratibha Patil" },answer: "C",image: null}
];